### Created by Bruno Carlos Dos Santos Melício
#### Lecturer, PhD Computer Science student, Eötvös Loránd University, Faculty of Informatics
#### AI Researcher, Neural Information Processing Group
#### https://www.linkedin.com/in/bruno-melicio/

jupyter nbconvert Documents/University/ELTE/Teaching/2022_2023/"Autumn Semester"/"Deep Network Development"/Lectures/"Lecture 5"/"5.1.Transposed_Convolutions.ipynb" --to slides --post serve

![title](images/segmentation.png)

# Transposed Convolutions

![title](https://miro.medium.com/max/1400/1*uk4KJEtyDuPOipfG4yd-WA.gif)

Necessary imports for this notebook

In [1]:
import torch
import torch.nn as nn

General formulas to know for this notebook

#### General formula for calculating the output size of a Convolution layer

Input size: $ c \times h \times w $

Filter: size $ c \times f \times f $ , stride $ s $ , padding $ p $ , number of filters $ m $


Output size: $ [ \; \frac{h + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; \frac{w + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; m \; ] $

#### General formula for calculating the output size of a Transposed Convolution layer

Input size: $ c \times h \times w $

Filter: size $ c \times f \times f $ , stride $ s $ , padding $ p $ , number of filters $ m $


Output size: $ [ \; (h - 1) * s - 2p + (f - 1) + 1 \; ] \;\; \times \;\; [ \; (w - 1) * s - 2p + (f - 1) + 1 \; ] \; \times \; [ \; m \; ] $

## 1. Convolution on 1D input

#### Input size: 5

#### Filter: size=3 , stride=2 , padding=0 , number of filters=1

![title](images/conv1d1.png)

#### Formula for calculating the output size of a Convolution layer on 1D example

Input size: $ 5 $

Filter: $ f = 3 $ , $ s = 2 $ , $ p = 0 $ , number of filters $ 1 $


Output size: $ [ \; \frac{h + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; \frac{w + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; m \; ] $

Output size: $ \frac{h + 2p - f}{s} + 1  $

Output size: $ \frac{5 + 2*0 - 3}{2} + 1  $

Output size: $ \frac{2}{2} + 1  $

Output size: $ 2 $

![title](images/conv1d2.png/)

![title](images/conv1d3.png)

![title](images/conv1d4.png)

Same example in PyTorch

We'll use the Conv1d from torch.nn

In [2]:
#Create a tensor of size (number_of_channels,length) with random values
input_conv1d = torch.randn(1,5)

print("Input shape:", input_conv1d.shape)
print("Input values:", input_conv1d)

Input shape: torch.Size([1, 5])
Input values: tensor([[-1.1382, -0.0638,  0.5016, -0.7053,  0.0324]])


In [3]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3
#with stride 2 and padding 0 (valid).
conv1d = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)

print(f'Conv 1d \n bias {conv1d.bias} \n and \n weights {conv1d.weight}')

Conv 1d 
 bias Parameter containing:
tensor([0.4477], requires_grad=True) 
 and 
 weights Parameter containing:
tensor([[[ 0.5708, -0.5294,  0.3098]]], requires_grad=True)


![title](images/bias.png)

In [4]:
output_conv1d = conv1d(input_conv1d)
print("Output shape: ", output_conv1d.shape)
print("Output values: ", output_conv1d)

Output shape:  torch.Size([1, 2])
Output values:  tensor([[-0.0128,  1.1174]], grad_fn=<SqueezeBackward1>)


## 2. Transposed Convolution on 1D input

**Notes**

The **Transposed Convolutional Layer** is also (wrongfully) known as the Deconvolutional layer.
A deconvolutional layer reverses the operation of a standard convolutional layer i.e. if the output generated through a standard convolutional layer is deconvolved, you get back the original input. 

The transposed convolutional layer is similar to the deconvolutional layer in the sense that the spatial dimension generated by both are the same. But **Transposed convolution doesn’t reverse the standard convolution by values, rather by dimensions only**.

#### Input size: 2

#### Filter: size=3 , stride=2 , padding=0 , number of filters=1

![title](images/transconv1d1.png)

#### Formula for calculating the output size of a Transposed Convolution layer on 1D example

Input size: $ 2 $

Filter: $ f = 3 $ , $ s = 2 $ , $ p = 0 $ , number of filters $ 1 $


Output size: $ [ \; (h - 1) * s - 2p + (f - 1) + 1 \; ] \;\; \times \;\; [ \; (w - 1) * s - 2p + (f - 1) + 1 \; ] \; \times \; [ \; m \; ] $

Output size: $ (2 - 1) * 2 - 2*0 + (3 - 1) + 1  $

Output size: $ 1*2 - 0 + 2 + 1 $

Output size: $ 5 $

![title](images/transconv1d2.png)

![title](images/transconv1d3.png)

![title](images/transconv1d4.png)

![title](images/transconv1d5.png)

Same example in PyTorch

We'll use the ConvTranspose1d from torch.nn

In [5]:
#Create a tensor of size (number_of_channels,length) with random values
input_transconv1d = torch.randn(1,2)

print("Input shape:", input_transconv1d.shape)
print("Input values:", input_transconv1d)

Input shape: torch.Size([1, 2])
Input values: tensor([[0.0304, 0.7709]])


In [6]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3
#with stride 2 and padding 0(valid).
convtrans1d = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)

print(f'Conv Transpose 1d \n bias {convtrans1d.bias} \n and \n weights {convtrans1d.weight}')

Conv Transpose 1d 
 bias Parameter containing:
tensor([-0.1669], requires_grad=True) 
 and 
 weights Parameter containing:
tensor([[[-0.5260,  0.2385, -0.0172]]], requires_grad=True)


In [7]:
output_transconv1d = convtrans1d(input_transconv1d)
print("Output shape: ", output_transconv1d.shape)
print("Output values: ", output_transconv1d)

Output shape:  torch.Size([1, 5])
Output values:  tensor([[-0.1829, -0.1597, -0.5729,  0.0170, -0.1802]],
       grad_fn=<SqueezeBackward1>)


## 3. Convolution with padding on 1D input 

#### Input size: 5

#### Filter: size=3 , stride=2 , padding=1 , number of filters=1

![title](images/conv1dpad1.png)

#### Formula for calculating the output size of a Convolution layer with padding on 1D example

Input size: $ 5 $

Filter: $ f = 3 $ , $ s = 2 $ , $ p = 1 $ , number of filters $ 1 $


Output size: $ [ \; \frac{h + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; \frac{w + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; m \; ] $

Output size: $ \frac{h + 2p - f}{s} + 1  $

Output size: $ \frac{5 + 2*1 - 3}{2} + 1  $

Output size: $ \frac{4}{2} + 1  $

Output size: $ 3 $

![title](images/conv1dpad2.png/)

![title](images/conv1dpad3.png/)

![title](images/conv1dpad4.png/)

![title](images/conv1dpad5.png/)

Same example in PyTorch

We'll use the Conv1d from torch.nn

In [8]:
#Create a tensor of size (number_of_channels,length) with random values
input_conv1d_pad = torch.randn(1,5)

print("Input shape:", input_conv1d_pad.shape)
print("Input values:", input_conv1d_pad)

Input shape: torch.Size([1, 5])
Input values: tensor([[-0.6996,  1.2482, -1.5919, -2.1097, -0.1708]])


In [9]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3
#with stride 2 and padding 1.
conv1d_pad = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)

print(f'Conv 1d \n bias {conv1d_pad.bias} \n and \n weights {conv1d_pad.weight}')

Conv 1d 
 bias Parameter containing:
tensor([0.0536], requires_grad=True) 
 and 
 weights Parameter containing:
tensor([[[-0.2986,  0.5761,  0.4801]]], requires_grad=True)


In [10]:
output_conv1d_pad = conv1d_pad(input_conv1d_pad)
print("Output shape: ", output_conv1d_pad.shape)
print("Output values: ", output_conv1d_pad)

Output shape:  torch.Size([1, 3])
Output values:  tensor([[ 0.2499, -2.2492,  0.5852]], grad_fn=<SqueezeBackward1>)


## 4. Transposed Convolution with padding on 1D input 

### First let's see it without padding

#### Formula for calculating the output size of a Transposed Convolution layer on 1D example

Input size: $ 3 $

Filter: $ f = 3 $ , $ s = 2 $ , $ p = 0 $ , number of filters $ 1 $

Output size: $ [ \; (h - 1) * s - 2p + (f - 1) + 1 \; ] \;\; \times \;\; [ \; (w - 1) * s - 2p + (f - 1) + 1 \; ] \; \times \; [ \; m \; ] $

Output size: $ (3 - 1) * 2 - 2*0 + (3 - 1) + 1  $

Output size: $ 2*2 + 2 + 1 $

Output size: $ 7 $

#### Without padding

![title](images/transconv1dpad0.png)

### Now, if we add padding

#### Formula for calculating the output size of a Transposed Convolution layer on 1D example

Input size: $ 3 $

Filter: $ f = 3 $ , $ s = 2 $ , $ p = 1 $ , number of filters $ 1 $

Output size: $ [ \; (h - 1) * s - 2p + (f - 1) + 1 \; ] \;\; \times \;\; [ \; (w - 1) * s - 2p + (f - 1) + 1 \; ] \; \times \; [ \; m \; ] $

Output size: $ (3 - 1) * 2 - 2*1 + (3 - 1) + 1  $

Output size: $ 2*2 - 2 + 2 + 1 $

Output size: $ 5 $

#### Now, if we add padding

![title](images/transconv1dpad2.png)

### Now, if we add padding

#### Input size: 3

#### Filter: size=3 , stride=2 , padding=1 , number of filters=1

#### Output size: 5

![title](images/transconv1dpad3.png)

### With padding

#### Input size: 3

#### Filter: size=3 , stride=2 , padding=1 , number of filters=1

#### Output size: 5

![title](images/transconv1dpad4.png)

### Now, if we add padding

#### Input size: 3

#### Filter: size=3 , stride=2 , padding=1 , number of filters=1

#### Output size: 5

![title](images/transconv1dpad5.png)

### With padding

#### Input size: 3

#### Filter: size=3 , stride=2 , padding=1 , number of filters=1

#### Output size: 5

![title](images/transconv1dpad6.png)

### With padding

#### Input size: 3

#### Filter: size=3 , stride=2 , padding=1 , number of filters=1

#### Output size: 5

![title](images/transconv1dpad7.png)

### With padding

#### Input size: 3

#### Filter: size=3 , stride=2 , padding=1 , number of filters=1

#### Output size: 5

![title](images/transconv1dpad8.png)

Same example in PyTorch

We'll use the ConvTranspose1d from torch.nn

In [11]:
#Create a tensor of size (number_of_channels,length) with random values
input = torch.tensor([[1, 2, 3]])

print("Input shape:", input.shape)
print("Input values:", input)

Input shape: torch.Size([1, 3])
Input values: tensor([[1, 2, 3]])


In [12]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3 with stride 2 and padding 0(valid).
convtrans1d = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, bias=False)

convtrans1d.weight.data = torch.nn.parameter.Parameter(torch.LongTensor([[[2, 2, 2]]]), requires_grad=False)

print(f'Conv Transpose 1d weights {convtrans1d.weight}')

Conv Transpose 1d weights Parameter containing:
tensor([[[2, 2, 2]]], requires_grad=True)


In [13]:
with torch.no_grad():
    output = convtrans1d(input)
print("Output shape: ", output.shape)
print("Output values: ", output)

Output shape:  torch.Size([1, 5])
Output values:  tensor([[ 2,  6,  4, 10,  6]])


## Summary of Convolution vs Transposed Convolution on 1D input

![title](images/transconv1dpad9.png)

###### Remarks
Different from in the regular convolution where padding is applied to input, in the transposed convolution it is applied to output. For example, when specifying the padding number on either side of the height and width as 1, the first and last rows will be removed from the transposed convolution output.

In the transposed convolution, strides are specified for intermediate results (thus output), not for input.

## 5. Convolution on 2D input

#### Input size: $ 5 \times 5 $

#### Filter: size $ = 3 \times 3 $ , stride $ = 2 $ , padding $ = 0 $ , number of filters $ = 1 $

![title](images/conv2d1.png)

#### Formula for calculating the output size of a Convolution layer on 2D example

Input size: $ 5 \times 5 $

Filter: $ f = 3 \times 3 $ , $ s = 2 $ , $ p = 0 $ , number of filters $ 1 $


Output size: $ [ \; \frac{h + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; \frac{w + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; m \; ] $

Output size: $ [ \; \frac{h + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; \frac{w + 2p - f}{s} + 1 \; ]  $

Output size: $ [ \; \frac{5 + 2*0 - 3}{2} + 1 \; ] \;\; \times \;\; [ \; \frac{5 + 2*0 - 3}{2} + 1 \; ]  $

Output size: $ [ \; \frac{2}{2} + 1 \; ] \;\; \times \;\; [ \; \frac{2}{2} + 1 \; ]  $

Output size: $ 2 \;\; \times \;\; 2$

![title](images/conv2d2.png/)

![title](images/conv2d3.png/)

![title](images/conv2d4.png/)

![title](images/conv2d5.png/)

![title](images/conv2d6.png/)

Same example in PyTorch

We'll use the Conv2d from torch.nn

In [14]:
#Create a tensor of size (number_of_channels,hieght, width) with random values
input_conv2d = torch.randn(1,5,5)

print("Input shape:", input_conv2d.shape)
print("Input values:", input_conv2d)

Input shape: torch.Size([1, 5, 5])
Input values: tensor([[[-1.0751, -2.1508, -0.1283,  0.9323, -1.0028],
         [ 0.4339,  0.8030, -1.0122, -0.7672, -1.2298],
         [ 0.7407,  0.5361, -0.6382, -1.2179,  2.5446],
         [ 0.7757,  0.1987,  0.3162, -2.2623, -0.5739],
         [ 0.5951,  0.6182, -0.1658,  0.1329,  0.2192]]])


In [15]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3
#with stride 2 and padding 0 (valid).
conv2d = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)

print(f'Conv 2d \n bias {conv2d.bias} \n and \n weights {conv2d.weight}')

Conv 2d 
 bias Parameter containing:
tensor([-0.2031], requires_grad=True) 
 and 
 weights Parameter containing:
tensor([[[[-0.1840,  0.3019, -0.1618],
          [ 0.1766, -0.2757,  0.0138],
          [-0.1580,  0.0477, -0.0536]]]], requires_grad=True)


In [16]:
output_conv2d = conv2d(input_conv2d)
print("Output shape: ", output_conv2d.shape)
print("Output values: ")
print(output_conv2d)

Output shape:  torch.Size([1, 2, 2])
Output values: 
tensor([[[-0.8498,  0.1863],
         [-0.0434, -0.1726]]], grad_fn=<SqueezeBackward1>)


## 6. Transposed Convolution on 2D input

#### Input size: $ 2 \times 2 $

#### Filter: size $ = 3 \times 3 $ , stride $ = 2 $ , padding $ = 0 $ , number of filters $ = 1 $

![title](images/transconv2d1.png)

#### Formula for calculating the output size of a Transposed Convolution layer on 2D example

Input size: $ 2 \times 2 $

Filter: $ f = 3 \times 3 $ , $ s = 2 $ , $ p = 0 $ , number of filters $ 1 $


Output size: $ [ \; (h - 1) * s - 2p + (f - 1) + 1 \; ] \;\; \times \;\; [ \; (w - 1) * s - 2p + (f - 1) + 1 \; ] \; \times \; [ \; m \; ] $

Output size: $ [ \; (h - 1) * s - 2p + (f - 1) + 1 \; ] \;\; \times \;\; [ \; (w - 1) * s - 2p + (f - 1) + 1 \; ]  $

Output size: $ [ \; (2 - 1) * 2 - 2*0 + (3 - 1) + 1 \; ] \;\; \times \;\; [ \; (2 - 1) * 2 - 2*0 + (3 - 1) + 1 \; ] $

Output size: $ [ \; 2 + 2 + 1 \; ] \;\; \times \;\; [ \; 2 + 2 + 1 \; ] $

Output size: $ 5 \;\; \times \;\; 5 $

![title](images/transconv2d2.png)

![title](images/transconv2d3.png)

### + means that there was some value there already, so we add them together

![title](images/transconv2d4.png)

![title](images/transconv2d5.png)


![title](images/transconv2d6.png)

Same example in PyTorch

We'll use the ConvTranspose2d from torch.nn

In [17]:
#Create a tensor of size (number_of_channels,height,width) with random values
input_convtrans2d = torch.randn(1,2,2)

print("Input shape:", input_convtrans2d.shape)
print("Input values:", input_convtrans2d)

Input shape: torch.Size([1, 2, 2])
Input values: tensor([[[ 0.6027, -0.6806],
         [-1.0898,  0.5117]]])


In [18]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3
# with stride 2 and padding 0(valid).
convtrans2d = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)

print(f'Conv Transpose 2d \n bias {convtrans2d.bias} \n and \n weights {convtrans2d.weight}')

Conv Transpose 2d 
 bias Parameter containing:
tensor([-0.1117], requires_grad=True) 
 and 
 weights Parameter containing:
tensor([[[[ 0.0111,  0.1212, -0.3294],
          [-0.0625,  0.0460,  0.0521],
          [ 0.0505, -0.2416, -0.0190]]]], requires_grad=True)


In [19]:
output_convtrans2d = convtrans2d(input_convtrans2d)
print("Output shape: ", output_convtrans2d.shape)
print("Output values: ")
print(output_convtrans2d)

Output shape:  torch.Size([1, 5, 5])
Output values: 
tensor([[[-0.1050, -0.0387, -0.3178, -0.1942,  0.1125],
         [-0.1494, -0.0840, -0.0378, -0.1431, -0.1472],
         [-0.0934, -0.3894,  0.2071,  0.1147, -0.2673],
         [-0.0436, -0.1619, -0.2005, -0.0882, -0.0851],
         [-0.1668,  0.1516, -0.0652, -0.2354, -0.1215]]],
       grad_fn=<SqueezeBackward1>)


## 7. Convolution with padding on 2D input 

#### Input size: $ 5 \times 5 $

#### Filter: size $ = 3 \times 3 $ , stride $ = 2 $ , padding $ = 1 $ , number of filters $ = 1 $

![title](images/conv2dpad1.png)

#### Formula for calculating the output size of a Convolution layer with padding on 2D example

Input size: $ 5 \times 5 $

Filter: $ f = 3 \times 3 $ , $ s = 2 $ , $ p = 1 $ , number of filters $ 1 $


Output size: $ [ \; \frac{h + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; \frac{w + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; m \; ] $

Output size: $ [ \; \frac{h + 2p - f}{s} + 1 \; ] \;\; \times \;\; [ \; \frac{w + 2p - f}{s} + 1 \; ]  $

Output size: $ [ \; \frac{5 + 2*1 - 3}{2} + 1 \; ] \;\; \times \;\; [ \; \frac{5 + 2*1 - 3}{2} + 1 \; ]  $

Output size: $ [ \; \frac{4}{2} + 1 \; ] \;\; \times \;\; [ \; \frac{4}{2} + 1 \; ]  $

Output size: $ 3 \;\; \times \;\; 3 $

![title](images/conv2dpad2.png/)

![title](images/conv2dpad3.png/)

![title](images/conv2dpad4.png/)

![title](images/conv2dpad5.png/)

Same example in PyTorch

We'll use the Conv2d from torch.nn

In [20]:
#Create a tensor of size (number_of_channels,height,width) with random values
input_conv2dpad = torch.randn(1,5,5)

print("Input shape:", input_conv2dpad.shape)
print("Input values:", input_conv2dpad)

Input shape: torch.Size([1, 5, 5])
Input values: tensor([[[ 0.9523,  0.0579,  1.8730, -0.7749,  0.7560],
         [-0.0473,  0.1938,  1.4323, -1.5268, -1.2933],
         [ 1.0163,  0.2373,  0.0404,  1.7097,  0.0641],
         [ 1.1040,  0.4448,  0.4397, -0.8689, -0.9529],
         [ 0.6624,  0.8765,  0.3704,  0.8393,  0.1468]]])


In [21]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3
#with stride 2 and padding 0 (valid).
conv2dpad = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)

print(f'Conv 2d \n bias {conv2dpad.bias} \n and \n weights {conv2dpad.weight}')

Conv 2d 
 bias Parameter containing:
tensor([-0.2810], requires_grad=True) 
 and 
 weights Parameter containing:
tensor([[[[ 0.1735,  0.1917,  0.2259],
          [-0.2998,  0.0672, -0.1904],
          [-0.0519, -0.0996, -0.0334]]]], requires_grad=True)


In [22]:
output_conv2dpad = conv2dpad(input_conv2dpad)
print("Output shape: ", output_conv2dpad.shape)
print("Output values: ")
print(output_conv2dpad)

Output shape:  torch.Size([1, 3, 3])
Output values: 
tensor([[[-0.2298, -0.1267,  0.2102],
         [-0.3481, -0.7494, -1.1622],
         [-0.0913, -0.7135, -0.8563]]], grad_fn=<SqueezeBackward1>)


## 8. Transposed Convolution with padding on 2D input 

#### Input size: $ 3 \times 3 $

#### Filter: size $ = 3 \times 3 $ , stride $ = 2 $ , padding $ = 1 $ , number of filters $ = 1 $

![title](images/transconv2dpad1.png)

#### Formula for calculating the output size of a Transposed Convolution layer with padding on 2D example

Input size: $ 3 \times 3 $

Filter: $ f = 3 \times 3 $ , $ s = 2 $ , $ p = 1 $ , number of filters $ 1 $


Output size: $ [ \; (h - 1) * s - 2p + (f - 1) + 1 \; ] \;\; \times \;\; [ \; (w - 1) * s - 2p + (f - 1) + 1 \; ] \; \times \; [ \; m \; ] $

Output size: $ [ \; (h - 1) * s - 2p + (f - 1) + 1 \; ] \;\; \times \;\; [ \; (w - 1) * s - 2p + (f - 1) + 1 \; ]  $

Output size: $ [ \; (3 - 1) * 2 - 2*0 + (3 - 1) + 1 \; ] \;\; \times \;\; [ \; (3 - 1) * 2 - 2*0 + (3 - 1) + 1 \; ] $

Output size: $ [ \; 4 + 2 + 1 \; ] \;\; \times \;\; [ \; 4 + 2 + 1 \; ] $

Output size: $ 5 \;\; \times \;\; 5 $

![title](images/transconv2dpad2.png)

![title](images/transconv2dpad3.png)

![title](images/transconv2dpad4.png)

![title](images/transconv2dpad5.png)

![title](images/transconv2dpad6.png)

Same example in PyTorch

We'll use the ConvTranspose2d from torch.nn

In [23]:
#Create a tensor of size (number_of_channels,height,width) with random values
input_convtrans2dpad = torch.randn(1,3,3)

print("Input shape:", input_convtrans2dpad.shape)
print("Input values:", input_convtrans2dpad)

Input shape: torch.Size([1, 3, 3])
Input values: tensor([[[ 0.4484, -0.5434,  1.2422],
         [-0.1515, -0.4509,  0.0134],
         [ 0.2276, -1.3005, -0.1960]]])


In [24]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3
#with stride 2 and padding 0(valid).
convtrans2dpad = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)

print(f'Conv Transpose 1d \n bias {convtrans2dpad.bias} \n and \n weights {convtrans2dpad.weight}')

Conv Transpose 1d 
 bias Parameter containing:
tensor([-0.1769], requires_grad=True) 
 and 
 weights Parameter containing:
tensor([[[[ 0.1874,  0.1409,  0.2798],
          [ 0.3012, -0.3260,  0.1793],
          [ 0.3301, -0.0348, -0.1889]]]], requires_grad=True)


In [25]:
output_convtrans2dpad = convtrans2dpad(input_convtrans2dpad)
print("Output shape: ", output_convtrans2dpad.shape)
print("Output values: ")
print(output_convtrans2dpad)

Output shape:  torch.Size([1, 5, 5])
Output values: 
tensor([[[-3.2311e-01, -2.6021e-01,  2.1251e-04,  9.9770e-02, -5.8186e-01],
         [-2.1389e-01, -5.6794e-01, -2.2155e-01,  2.1214e-01, -2.1831e-01],
         [-1.2757e-01, -3.3991e-01, -2.9964e-02, -2.5376e-01, -1.8130e-01],
         [-1.3960e-01, -4.7728e-01, -3.4449e-01, -4.8799e-01, -2.0502e-01],
         [-2.5112e-01, -5.2786e-01,  2.4700e-01, -4.6918e-01, -1.1306e-01]]],
       grad_fn=<SqueezeBackward1>)


#### Example

![title](images/transconv2dpad7.png)

In [26]:
#Create a tensor of size (number_of_channels,length) with random values
input_example = torch.tensor([[[1, 2], [3,4]]])

print("Input shape:", input_example.shape)
print("Input values:")
print(input_example)

Input shape: torch.Size([1, 2, 2])
Input values:
tensor([[[1, 2],
         [3, 4]]])


In [27]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3 with stride 2 and padding 0(valid).
convtrans2d_example = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, bias=False)

convtrans2d_example.weight.data = torch.nn.parameter.Parameter(torch.LongTensor([[[[2, 2, 2],[1,0,1],[2,2,2]]]]), requires_grad=False)

print(f'Conv Transpose 2d weights {convtrans2d_example.weight}')

Conv Transpose 2d weights Parameter containing:
tensor([[[[2, 2, 2],
          [1, 0, 1],
          [2, 2, 2]]]], requires_grad=True)


In [28]:
with torch.no_grad():
    output_example = convtrans2d_example(input_example)
print("Output shape: ", output_example.shape)
print("Output values: ")
print(output_example)

Output shape:  torch.Size([1, 3, 3])
Output values: 
tensor([[[ 0,  3,  0],
         [ 8, 20, 12],
         [ 0,  7,  0]]])


## More examples with Transposed Convolutions

#### Multiple filters

In [29]:
#Create a tensor of size (number_of_channels,height,width) with random values
input_filters = torch.randn(3,64,64)

print("Input shape:", input_filters.shape)
#print("Input values:", input_example)

Input shape: torch.Size([3, 64, 64])


In [30]:
#The conv1d will receive an input with 1 channel only and we will apply a single filter of size 3
#with stride 2 and padding 0(valid).
convtrans2d_filters = nn.ConvTranspose2d(in_channels=3, out_channels=16, kernel_size=3, stride=2, padding=1, bias=False)

print(f'Conv Transpose 2d weights {convtrans2d_filters.weight}')

Conv Transpose 2d weights Parameter containing:
tensor([[[[-9.1355e-03, -2.6638e-03, -6.3337e-02],
          [-3.8365e-02,  6.5016e-02,  3.2665e-02],
          [ 8.1736e-02, -6.4391e-02,  4.8840e-02]],

         [[ 9.2116e-03,  5.9166e-02, -4.6845e-02],
          [-5.1453e-02, -5.7589e-02, -2.3312e-02],
          [-6.8373e-02, -4.0026e-02,  3.9030e-02]],

         [[-7.5746e-02, -4.1416e-02,  4.3222e-02],
          [-1.5122e-02,  8.0036e-03,  7.2035e-02],
          [ 1.2169e-02, -4.5729e-02,  6.3416e-02]],

         [[-7.1949e-02, -1.9258e-02,  2.1425e-02],
          [ 1.8752e-02,  7.1734e-02,  6.8429e-02],
          [ 3.3618e-02,  5.2805e-03, -1.6940e-02]],

         [[ 5.9031e-02,  2.2882e-02,  2.1934e-02],
          [-6.5741e-02, -6.0560e-02, -2.4406e-02],
          [ 1.7699e-02, -2.1670e-02,  5.2627e-02]],

         [[ 4.0107e-02, -3.4530e-02, -1.4231e-02],
          [-2.7707e-02, -8.5565e-04,  1.2299e-02],
          [ 1.3706e-02, -3.6508e-02, -1.3522e-02]],

         [[ 6.0392e-02

In [31]:
output_filters = convtrans2d_filters(input_filters)
print("Output shape: ", output_filters.shape)
#print("Output values: ")
#print(output_example)

Output shape:  torch.Size([16, 127, 127])


#### Resources
https://d2l.ai/chapter_computer-vision/transposed-conv.html

https://www.youtube.com/watch?v=ilkSwsggSNM